#let MAIN_COLOR = rgb(138, 15, 29)
#let SECONDARY_COLOR = luma(240)
#let INTENSE_COLOR = rgb(255, 157, 28)
#let SYMPATHETIC_COLOR_1 = rgb(36, 181, 118)
#let CODE_SNIPPET_COLOR = luma(210)

#let WARN_PRIMARY_COLOR = INTENSE_COLOR
#let WARN_SECONDARY_COLOR = INTENSE_COLOR.darken(20%)

#let NOTE_PRIMARY_COLOR = SYMPATHETIC_COLOR_1
#let NOTE_SECONDARY_COLOR = SYMPATHETIC_COLOR_1.darken(20%)
